cc_library(
  name = "parser",
  srcs = [
    "parser.cpp",
  ],
  hdrs = [
    "environment.hpp",
    "parser.hpp",
  ],
  deps = [
    "//cpp/lexer:lexer",
    "//cpp/inter:inter",
  ],
  visibility = [
    "//cpp:__subpackages__",
  ],
)
