cc_library(
  name = "lexer",
  srcs = [
    "lexer.cpp",
    "token.cpp",
    "type.cpp",
    "word.cpp",
  ],
  hdrs = [
    "array.hpp",
    "lexer.hpp",
    "numeric.hpp",
    "token.hpp",
    "type.hpp",
    "word.hpp",
  ],
  visibility = [
  "//cpp:__subpackages__",
  ],
)
